service:
  name: jawsug-niigata-20190914

frameworkVersion: '>=1.0.0 <2.0.0'

custom:
  bucketName: ${self:service.name}-${self:provider.stage}
  layerName: ${self:service.name}-${self:provider.stage}-imagemagick
  tableName: ${self:service.name}-${self:provider.stage}

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'} 
  region: ${opt:region, 'ap-northeast-1'}
  profile: default
  memorySize: 128
  timeout: 300
  logRetentionInDays: 14
  iamRoleStatements: # IAM role statements so that services can be accessed in the AWS account
    - Effect: 'Allow'
      Action:
        - 's3:ListObject'
        - 's3:GetObject'
        - 's3:PutObject'
        - 's3:ListBucket'
      Resource:
        - 'arn:aws:s3:::${self:custom.bucketName}'
        - 'arn:aws:s3:::${self:custom.bucketName}/*'
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:custom.tableName}"



package:
  exclude:
    - node_modules/**
    - src/**
    - package.json
    - tsconfig.json
    - yarn.lock
    - imagemagick-aws-lambda-2/**
    - .cache/**
    - build_im.sh

functions:
  thumbnail:
    handler: handler.thumbnail
    name: ${self:provider.stage}-thumbnail
    description: thumbnail
    memorySize: 128
    runtime: nodejs10.x
    layers:
      - { Ref: ImagemagickLambdaLayer }
    events:
      - s3:
          bucket: '${self:custom.bucketName}'
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
  api:
    handler: handler.api
    name: ${self:provider.stage}-api
    description: api
    memorySize: 128
    runtime: nodejs10.x
    environment:
      BUCKET: ${self:custom.bucketName}
      TABLE: ${self:custom.tableName}
    events:
      - http:
          path: "{proxy+}"
          method: ANY
          cors: true
  wsConnectHandler:
    handler: handler.onconnect
    environment:
      TABLE: ${self:custom.tableName}
    events:
      - websocket: $connect
  wsDisconnectHandler:
    handler: handler.ondisconnect
    environment:
      TABLE: ${self:custom.tableName}
    events:
      - websocket: $disconnect


layers:
  imagemagick:
    path: imagemagick-aws-lambda-2/result
    name: ${self:custom.layerName}
    description: for imagemagick
    compatibleRuntimes:
      - nodejs10.x


resources:
  Resources:
    S3BucketJawsugniigata20190914dev:
      Type: AWS::S3::Bucket
      Properties:
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins: 
                - "*"
              AllowedMethods: 
                - POST
                - PUT
              AllowedHeaders: 
                - "*"
    DynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
